minio:
  host: "49.233.41.155"
  port: "9000"
  access_key_id: ""
  secret_access_key: ""
  avatar_buckets: avatar
  avatar_path: ""

log:
  level: "debug"
  file_name: "user.log"
  log_path: "/"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "49.233.41.155"
  port: "3306"
  database: "bastion_brotherhood"
  username: "root"
  password: "123456"
  max_idle_conn: 10
  max_open_conn: 100
  max_idle_time: 30
